// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmULpQpWjJvyIt4ENJVqful6f0Qz_hNs',
    appId: '1:1004451287188:web:c40955dafb0d7632de6481',
    messagingSenderId: '1004451287188',
    projectId: 'textnot-11010',
    authDomain: 'textnot-11010.firebaseapp.com',
    storageBucket: 'textnot-11010.firebasestorage.app',
    measurementId: 'G-DH7HLMV6PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBawGEkiLpPavE1TkxVyhWpBZ8cxB5xgk',
    appId: '1:1004451287188:android:1f2f80a3bc1fe890de6481',
    messagingSenderId: '1004451287188',
    projectId: 'textnot-11010',
    storageBucket: 'textnot-11010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp8n19EnEO_X9UtptXtULXRvAcJQDdb8s',
    appId: '1:1004451287188:ios:8041d9d72e8816adde6481',
    messagingSenderId: '1004451287188',
    projectId: 'textnot-11010',
    storageBucket: 'textnot-11010.firebasestorage.app',
    iosBundleId: 'com.example.tsakwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp8n19EnEO_X9UtptXtULXRvAcJQDdb8s',
    appId: '1:1004451287188:ios:8041d9d72e8816adde6481',
    messagingSenderId: '1004451287188',
    projectId: 'textnot-11010',
    storageBucket: 'textnot-11010.firebasestorage.app',
    iosBundleId: 'com.example.tsakwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsmULpQpWjJvyIt4ENJVqful6f0Qz_hNs',
    appId: '1:1004451287188:web:29da5d3a563eac46de6481',
    messagingSenderId: '1004451287188',
    projectId: 'textnot-11010',
    authDomain: 'textnot-11010.firebaseapp.com',
    storageBucket: 'textnot-11010.firebasestorage.app',
    measurementId: 'G-1F4FZ4FTDX',
  );
}
